### ISSUE TITLE
Zoom page lists duplicate meetings

### ISSUE THREAD

**Issue by skierx** [BostonDSA/members#10]
Example:

```
Dec 15, 2021
6:30 PM–8:30 PM
Zoom account: 1
Labor Working Group Meeting
```

```
Dec 15, 2021
6:30 PM–8:30 PM
Zoom account: 2
Labor Working Group Meeting
```

**Comment by skierx** [comment]
Wiki: https://wiki.bostondsa.org/view/How_to_set_up_a_Zoom_call
Code: https://github.com/BostonDSA/members/blob/main/zoom_meeting_fetcher.js

**Comment by danpmch** [comment]
From the output I take it that the same meeting is showing up for multiple accounts, but that leaves open the question of what the right solution is. I could see doing either of:

1. just pick one meeting to display
2. switch "Zoom account" display to "Zoom accounts" and list all accounts in one meeting entry

but I don't have enough context to know which solution is preferable.

**Comment by skierx** [comment]
The phantom events don't show up in the UI. https://wiki.bostondsa.org/view/How_to_set_up_a_Zoom_call. Here's an example:

![image](https://user-images.githubusercontent.com/1521517/150458302-bcef7058-4131-4d10-8a9a-65756919a9a3.png)

If you log in to the zoom accounts there is no event for Account 1, but it is there for Account 3.

My gut feeling is there is either a bug in the Node that is duplicating it when it's collecting the data or the Zoom API has various statuses included in the API response that the code is not filtering out things like rescheduled events.

**Comment by danpmch** [comment]
I've confirmed that the meeting is coming back from the zoom API for both accounts, so it's not a case of our node code duplicating it during collection. There's also no difference in the meeting json that comes back for the two accounts. There is a host_id, which I'm guessing will only correspond to one of the two accounts and could therefore be used to filter the returned meetings. But that doesn't explain why the meeting is showing up for the other account in the first place.

**Comment by danpmch** [comment]
It might be because the meeting has the info account ID as the `assistant_id`, apparently meaning that it was scheduled by the info account on behalf of the zoom account.
```
{
  uuid: 'w0d8QkgMSqekq6b6kL296g==',
  id: 81773513548,
  host_id: 'r0RjFP_JQJ2DDDZU1H7lkg',
  host_email: 'zoom@bostondsa.org',
  assistant_id: 'seMiINYmTnikKKlyuH4P1g',
  topic: 'No Cost Calls Working Group',
```
